### ISSUE TITLE
Vive trackers : prepend data with unique id

### ISSUE THREAD

**Issue by matcham** [worldmaking/vr#1]
The "vr-tracking-data" output sends position and orientations of my Vive trackers, but not prepended by any id or name
just 
print:  tracked_position 0.086986 0.594328 -1.442371
print:  tracked_quat 0.243485 0.671472 -0.656717 0.241998
print:  position 0.086986 0.594328 -1.442371
print:  quat 0.243485 0.671472 -0.656717 0.241998
print:  velocity 0.000512 0.000287 -0.000348
print:  angular_velocity -0.000059 -0.00051 -0.00074

so with multiple trackers... very hard actually to know who is who :-)

It would be much easier to add the unique id of each tracker just before each meassage 
for example :
123 tracked_position 0.086986 0.594328 -1.442371

**Comment by grrrwaaa** [comment]
This is now fixed.
