### ISSUE TITLE
error 126 loading external vr

### ISSUE THREAD

**Issue by fdiba** [worldmaking/vr#3]
Hello I get the message "error 126 loading external vr" when I try to open "vr.360.maxpat" or use vr object.

I have installed the visual studio 2015 redistributable package and I am using Max 7.0.3. 

Any idea ?

**Comment by grrrwaaa** [comment]
Hi, 

Yes usually this error means the visual studio 2015 redistributable package, or some other dependent library, is missing. There are some runtime dlls that are needed, these are packaged in the VR package under /support; if you install the VR package via Max's package manager, or manually put the VR package into your Documents/Max/Packages, then it should pick them up. Might need a restart. 

Is this 32- or 64-bit max? Can you paste the full error? It might identify what library is missing.

Thanks,

Graham

**Comment by fdiba** [comment]
I'm using 64-bit max and I have restarted my computer. I have downloaded the archive, unzipped it and pasted it in "Packages". I have also renamed the folder "VR". In the support folder I have for Win64 openvr_api.dll et phonon.dll.

Sadly, the full error message on the max console is "error 126 loading external vr".

**Comment by fdiba** [comment]
I have installed max 7.3.4 and downloaded the VR package using the package manager, now it works fine. I don't know exactly what wasn't working. Maybe the fact that viddll (anoher package that the VR package use ?) needed to be updated ?

**Comment by grrrwaaa** [comment]
Ah glad this was figured out! Not sure why it threw 126 error, but yes I guess the VR package depends on some rendering features added after Max 7.0.3
